// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBddz4TeprTwG24Gp5LrKWh0NnHOtY90hI',
    appId: '1:1029799637868:web:e964ae96912966b1f7f949',
    messagingSenderId: '1029799637868',
    projectId: 'umbrela-91cc0',
    authDomain: 'umbrela-91cc0.firebaseapp.com',
    storageBucket: 'umbrela-91cc0.appspot.com',
    measurementId: 'G-P2CV1S7QLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGOLcYOfaJCKlyMxMxeoQ2buYa6hX-dVA',
    appId: '1:1029799637868:android:de74f073bf5215ddf7f949',
    messagingSenderId: '1029799637868',
    projectId: 'umbrela-91cc0',
    storageBucket: 'umbrela-91cc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_xQY2NxDanxKLnYtV90QMGq7z5FnqQ_Q',
    appId: '1:1029799637868:ios:268908e772d4c4c5f7f949',
    messagingSenderId: '1029799637868',
    projectId: 'umbrela-91cc0',
    storageBucket: 'umbrela-91cc0.appspot.com',
    iosClientId: '1029799637868-443cc4pf41ce0m20irmllq0mbqj08tk5.apps.googleusercontent.com',
    iosBundleId: 'br.dev.douglaswender.umbrelaCash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_xQY2NxDanxKLnYtV90QMGq7z5FnqQ_Q',
    appId: '1:1029799637868:ios:268908e772d4c4c5f7f949',
    messagingSenderId: '1029799637868',
    projectId: 'umbrela-91cc0',
    storageBucket: 'umbrela-91cc0.appspot.com',
    iosClientId: '1029799637868-443cc4pf41ce0m20irmllq0mbqj08tk5.apps.googleusercontent.com',
    iosBundleId: 'br.dev.douglaswender.umbrelaCash',
  );
}
